[package]
name = "xkcd"
version = "0.1.0"
edition = "2018"

[dependencies]
image = "0.22.3"
rand = "0.7.2"
reqwest = "0.9.24"
serde = { version = "1.0.104", features = ["derive"] }
term_size = "0.3.1"
